name: Build AndUEDumper on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Download Android NDK with curl and extract
      shell: cmd
      run: |
        curl -L -o ndk.zip https://dl.google.com/android/repository/android-ndk-r21e-windows-x86_64.zip
        powershell -Command "Expand-Archive ndk.zip -DestinationPath %USERPROFILE%\android-ndk"
        del ndk.zip

    - name: Add NDK to PATH
      shell: powershell
      run: |
        echo "$Env:USERPROFILE\android-ndk\android-ndk-r21e" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

    - name: Run ndk-build.bat inside AndUEDumper folder
      shell: cmd
      run: cd AndUEDumper && ndk-build.bat

    - name: List build output files
      shell: cmd
      run: dir AndUEDumper\build /S

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AndUEDumper-build
        path: AndUEDumper\build\
